name: buildAndDeployApp

on: 
    push:
        branches:
         - simple-demo
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v3
            - name: Setup Node.js version
              uses: actions/setup-node@v4
              with: 
                node-version: '20.x'
            - name: Install Dependancies
              run: npm install 
            - name: Build Project
              run: npm run build
            - name: Run Tests
              run: npm test 

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                name: build
                path: |
                  build
                  !node_modules/
    
    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
        - name: Download build artifacts
          uses: actions/download-artifact@v4
          with:
            name: build
            path: build

        - name: Deploy to Azure Web App
          uses: azure/webapps-deploy@v2
          with:
            app-name: demo-test-v2
            publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}

        


    

            




